spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userdb?useSSL=false&serverTimezone=UTC
    username: root
    password:
  jpa:
    hibernate:
     ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: MYSQL